# Configuración de base de datos para AppFinanzas

# URL de conexión JDBC
db.url=jdbc:mysql://localhost:3306/bd_finanzas?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

# Usuario y contraseña de MySQL
db.user=root
# No subir contraseña a GITHUB
db.password=root
